on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 

name: "Trigger: Push action"
permissions: {}

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0
        env:
          SHELLCHECK_OPTS: -e SC1090 -e SC1091 -e SC2154
        with:
          version: v0.9.0

